## Why NumPy?
- It's fast
- Behind the scenes optimizations written in C
- Vectorization via broadcasting (avoiding loops)
- Backbone of other Python Scientific packages

## What are we going to cover?
- Most useful functions
- Numpy datatypes & attributes (ndarray)
- Creating arrays
- Viewing arrays and matrices
- Manipulating & comparing arrays
- Sorting arrays
- Use cases

In [1]:
import numpy as np
np.version.version

'1.19.2'

## DataTypes and Attributes 

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [12]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]])

a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [7]:
print(type(a2))
print(type(a3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a1.shape # shape of a vector is returned as a singleton tuple

(3,)

In [9]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [20]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [21]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [22]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [23]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [29]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [27]:
import pandas as pd

In [28]:
# Create a DataFrame from a NumPy array
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [33]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

In [36]:
ones = np.ones((2,3))

In [37]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
ones.dtype

dtype('float64')

In [39]:
type(ones)

numpy.ndarray

In [40]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [46]:
random_array = np.random.randint(0, 10, (3,5))
random_array

array([[5, 7, 5, 9, 2],
       [5, 1, 4, 4, 4],
       [1, 4, 5, 4, 9]])

In [47]:
random_array.size

15

In [48]:
random_array.shape

(3, 5)

In [53]:
random_array_2 = np.random.random((5,4))
random_array_2

array([[0.42385958, 0.0230594 , 0.96821599, 0.15264494],
       [0.45229087, 0.37462697, 0.73025827, 0.73057673],
       [0.90461285, 0.72954777, 0.77867484, 0.57649829],
       [0.40158289, 0.50331516, 0.389613  , 0.22032303],
       [0.37167194, 0.67357559, 0.33560336, 0.46826821]])

In [55]:
random_array_2.shape

(5, 4)

In [58]:
random_array_3 = np.random.rand(5,3)
random_array_3 # Notice how the syntax is slightly different than np.random.random

array([[0.26820526, 0.96413607, 0.67072977],
       [0.35955903, 0.22367056, 0.25114559],
       [0.81605612, 0.02824427, 0.85625699],
       [0.91274225, 0.24362045, 0.87632069],
       [0.26629456, 0.8914354 , 0.94030616]])

In [75]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(0,10,(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [67]:
random_array_4.shape

(5, 3)

## Viewing arrays and matrices 

In [76]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [77]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [79]:
a1[0]

1

In [80]:
a2[0]

array([1. , 2. , 3.3])

In [81]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [83]:
a3.shape

(2, 3, 3)

In [86]:
# Slicing
a3[:2,:2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [87]:
a4 = np.random.randint(0,10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

In [88]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [95]:
a4[1][1][0][:4]

array([0, 1, 2, 4])

## Manipulating & comparing arrays 

### Arithmetic

In [96]:
a1

array([1, 2, 3])

In [98]:
ones = np.ones((3,))
ones

array([1., 1., 1.])

In [100]:
a1 + ones

array([2., 3., 4.])

In [101]:
a1 - ones

array([0., 1., 2.])

In [102]:
a1 * ones

array([1., 2., 3.])

In [103]:
a1 / ones

array([1., 2., 3.])

In [104]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [106]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [107]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [109]:
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [112]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [113]:
a2.reshape((2,3,1))

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [114]:
a2.reshape((2,3,1)) * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [117]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [120]:
a2 // a1 # Floor division (rounds down)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [121]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [122]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [123]:
np.add(a1,ones)

array([2., 3., 4.])

In [124]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [126]:
np.mod(a1,2)

array([1, 0, 1], dtype=int32)

In [127]:
np.exp(a1) # e^x

array([ 2.71828183,  7.3890561 , 20.08553692])

In [128]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation 

Aggregation = peroforming the same operation on a number of things

In [129]:
listy_list = [1,2,3]
type(listy_list)

list

In [130]:
sum(listy_list)

6

In [131]:
a1

array([1, 2, 3])

In [132]:
sum(a1)

6

In [133]:
np.sum(a1)

6

### Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`)

In [134]:
# Creating a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [137]:
massive_array.shape, massive_array.ndim

((100000,), 1)

In [139]:
massive_array[:10]

array([0.16494046, 0.36980809, 0.14644176, 0.56961841, 0.70373728,
       0.28847644, 0.43328806, 0.75610669, 0.39609828, 0.89603839])

In [140]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's sum()

12.8 ms ± 283 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
34 µs ± 707 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [141]:
12800 / 34

376.47058823529414

### !!! np.sum is ~ 400 times faster than Python's sum method

In [142]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [143]:
np.sum(a2)

21.8

In [144]:
np.mean(a2)

3.6333333333333333

In [145]:
np.max(a2)

6.5

In [146]:
np.min(2)

2

In [147]:
np.std(a2)

1.8226964152656422

In [148]:
np.var(a2)

3.3222222222222224

In [149]:
# Variance = measure of the average degree to which each number is different from the mean
# Higher variance = wider range of numbers
# Lower variance = narrower range of numbers

In [150]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean

In [153]:
# Standard deviation = square root of variance
np.sqrt(np.var(a2))

1.8226964152656422